languageCode = "en-us"
title = "Rochester 2600"
baseurl = "https://rochester2600.github.io/"
publishDir = "docs"
theme = "after-dark"

builddrafts = true
canonifyurls = false
contentdir = "content"
author = "Rochester2600"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "UA-10542864-1" # Optional, add tracking Id for analytics
disqusShortname = "" # Optional, add Disqus shortname for comments
SectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

description = "Rochester, NY's hacker meetup" # Suggested, controls default description meta
author = "ROC2600" # Optional, controls author name display on posts
hide_author = true # Optional, set true to hide author name on posts
show_menu = true # Optional, set true to enable section menu
powered_by = false # Optional, set false to disable credits
images = [] # Suggested, adds default OpenGraph images
paginate = 5


[menu]
  [[menu.main]]
    name = "Home"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "News"
    weight = 1
    identifier = "news"
    url = "/news/"
  [[menu.main]]
    name = "About"
    weight = 2
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Presentations"
    weight = 3
    identifier = "presentations"
    url = "/presentations/"
